### PR TITLE
Basics prgmng a

### PR DESCRIPTION
**Pull request by wa1tnr**
slipped one in

### CODE REVIEW

**Review by MaderDash — COMMENTED** [review]
As this is a longer post, we may need to incorperate a table of contence at the top? Just an idea? Or something of that nature?  What do you think?

**Comment by MaderDash** [comment]
We may need to incorperate a table of contense? Because of the size of this page? Or break it into afew pages with like a next, button or something? Just some thoughts as its getting a bit long/large.

**Comment by wa1tnr** [comment]
> table of contents
 
 Did not once cross my mind.  Thanks!  Will do something about it 'soon' ;)

**Comment by MaderDash** [comment]
Going to merge this in now. Feel free to make more changes as you wish the next push will not go into effect untill sunday [4days from now] :D

**Comment by wa1tnr** [comment]
Thanks, Dash.  Got it: Sunday push. ;)

I'm just letting my wild horses run free, at the moment.  I figure if I write
what I want to, some of it will be useful to others.

This doesn't have to be the 'official' version of this TODO item (cover
'programming' as a succinct topic).

I look at my work more as 'raw materials' for others to work out.

This isn't easy; treading where so many have done such good,
illuminating writing on the subject. ;)

Sandbox has ongoing work, for lurkers:

https://github.com/wa1tnr/ard-disc-wiki-tnr-sandbox/blob/dvlp-dwnstrm/basicsOfProgramming.md-sbx.md

Enjoy (or pull your hair out, your choice ;)

**Pull request merged**
